### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by drglove** [mayerwin/vs-customize-window-title#10]
I have a solution that I often have open with multiple Visual Studio instances, that differ only by the environment variables passed in when VS is started. It would be awesome to be able to print the contents of an environment variable into the title, maybe with something like `[$myVar]`.

**Comment by mayerwin** [comment]
Hi @drglove. Check out version 3.3.6. I have added the tag [env:X] (usage: [env:myVar] instead of the syntax you suggest). Happy new year :).
