### ISSUE TITLE
Display user (administrator)?

### ISSUE THREAD

**Issue by zpqrtbnk** [mayerwin/vs-customize-window-title#11]
Thanks for an amazing extensions.

We are running VS as a "normal" user and in some cases in order to attach to eg IIS we run it elevated. By default, VS then changes "Microsoft Visual Studio" into "Microsoft Visual Studio (Administrator)". I guess it's the [ideName] that changes? But we'd rather get rid of "Microsoft Visual Studio" since, well, yes, obviously we're running VS. Any ways we could get the "(Administrator)" part of the name though?

**Comment by mayerwin** [comment]
It is not possible with the current version, however I will look into it. It could be solved in a more generic fashion with string manipulation feature suggested here https://github.com/mayerwin/vs-customize-window-title/issues/8 (not already implemented).
We could also add a dedicated tag "[ideNameWithoutName]" for a faster support, but not sure it is a good idea if the use case is not sufficiently common.

**Comment by zpqrtbnk** [comment]
Just thinking here, considering string manipulation or a complete scripting engine is probably is huge task... could do with an `[elevated]` tag that would only render when elevated, and display an "Elevated string" configured in _options / Patterns_.

So one could define that string to "(whatever)" and use a pattern of eg "`[solutionName][elevated]`", and when running elevated the title would become "My Solution (whatever)".

Happy to look into it and see if I can do a PR for it, if you think it's not too specific and has a chance to be useful.

**Comment by zpqrtbnk** [comment]
Have created PR https://github.com/mayerwin/vs-customize-window-title/pull/12

**Comment by mayerwin** [comment]
Hi, I have added the [elevationSuffix] tag in the latest release, it should fit the bill without needing to add an option just for this. I basically parse it from the IdeName (which includes the elevationSuffix).
