### ISSUE TITLE
Global override settings not being picked up

### ISSUE THREAD

**Issue by headsphere** [mayerwin/vs-customize-window-title#14]
Hi there - I have a global settings file set up to configure furthest parent depth, due to the structure of my SVN repository. The actual branch name in the path is configured to be a wildcard.

I have saved this file and configured the add-in to look at this config file using the "global settings override file path" setting. The problem is, however that the settings are completely ignored. The settings are being overridden by what is in the config dialog window, not the config file.

Is there somewhere else I need to set the addin to look at the config file, not at the config that is set up in the dialog window? Or is there something wrong with my config file? I've tried toggling the debug output but it doesn't give me any information apart from "RenameVSWindowTitle: Debugger context changed. Updating title."

Thanks!

```
<?xml version="1.0" encoding="utf-8"?>
<RenameVSWindowTitle>
  <SettingsSet
    Path="C:\SVN\branches\*\Primary\SubDir\MySolution-Primary.sln"
    SolutionName="MySolution-Primary"
    ClosestParentDepth="1"
    FarthestParentDepth="3"
    AppendedString="*"
    PatternIfRunningMode="[parentPath]\[solutionName] (Running) - [ideName]"
    PatternIfBreakMode="[parentPath]\[solutionName] (Debugging) - [ideName]"
    PatternIfDesignMode="[parentPath]\[solutionName] - [ideName]" />
  <SettingsSet
    Path="C:\SVN\branches\*\Secondary\MySolution-Secondary.sln"
    SolutionName="MySolution-Secondary"
    ClosestParentDepth="1"
    FarthestParentDepth="2"
    AppendedString="*"
    PatternIfRunningMode="[parentPath]\[solutionName] (Running) - [ideName]"
    PatternIfBreakMode="[parentPath]\[solutionName] (Debugging) - [ideName]"
    PatternIfDesignMode="[parentPath]\[solutionName] - [ideName]" />
</RenameVSWindowTitle>
```

**Comment by mayerwin** [comment]
Can you confirm you set "Enable solution-specific overrides" to true? This is necessary even for global configs (as global configs are still applied at the solution level with the wildcard).

You can also recheck to make sure the path actually listed in the input matches yours.

Let me know if this doesn't solve the issue.

**Comment by lexx9999** [comment]
Wildcard-matching is case sensitive, maybe that's an issue...

Does it work without wildcard in the path?
Is your config file opened when you click "open global config"?



@mayerwin 
To fix case sensitivity, I recommend to change this.
                            (path.Contains("*") || path.Contains("?")) && new Wildcard(path /* add here: */, RegexOptions.IgnoreCase).IsMatch(settings.SolutionFilePath);

**Comment by mayerwin** [comment]
Very good point, I'll change that as it can be rather unexpected for paths
on Windows.

**Comment by mayerwin** [comment]
I am in the middle of migrating the extension to support VS 2017.

**Comment by mayerwin** [comment]
I will also update the description of "Enable solution-specific overrides" to make it clear that it is needed for the global config file as well.

**Comment by headsphere** [comment]
Thanks @mayerwin  - that solved the problem

One other little thing however, I noticed that setting ClosestParentDepth, FarthestParentDepth don't seem to have any effect when setting them from a global config. The other attributes work fine, and indeed I can achieve what I want using the [parent:X] tags so its not a big issue, but thought I'd let you know to see if you can reproduce it on your machine

**Comment by mayerwin** [comment]
Good point, this is indeed a bug. I am fixing this right now and releasing a new version (3.4.1).

**Comment by ophite** [comment]
What about  VS 2017 ? I installed it - but seems to be it does not work

**Comment by mayerwin** [comment]
This should work normally. Can you clarify what is the issue you are encountering?

**Comment by ophite** [comment]
installed - but nothing changed (no full path in title)

**Comment by lexx9999** [comment]
@ophite By default it doesn't show the full path, just the direct parent folder name. Do you see an asterisk ("*") at the end of the title?
Do you see a section "Customize VS Window title" in options?

**Comment by ophite** [comment]
Yes i see it, how i can enable full path

**Comment by lexx9999** [comment]
Actually there are a number of ways to see the full path.
The simplest is goto options  "Customize VS Window title" - "Global rules" and set "Farthest parent folder path" to 99 (or any high enough number).

To see the full path including ".sln" you can replace "[parentPath]\[solutionName]" with "[parent:99:0]" in all patterns. You can use the pattern editor to preview the result, as you can see in the screenshot.
![image](https://user-images.githubusercontent.com/19334169/28692537-46f8d04a-7321-11e7-8524-b364ce73e5bc.png)
