### ISSUE TITLE
Cannot download plugin

### ISSUE THREAD

**Issue by aoakeson** [mayerwin/vs-customize-window-title#16]
When trying to download this plug in I am getting error: 

An error occurred while processing your request.
Reference #97.3e5f9e41.1488998323.18c10bb0

**Comment by mayerwin** [comment]
Are you downloading from Visual Studio or from the Marketplace? It works from the MarketPlace for sure, I don't see why it wouldn't from Visual Studio.
Can you try again? Also see if you can download other extensions? 
Visual Studio 2017 was just released so maybe Microsoft is having traffic management issues.

**Comment by aoakeson** [comment]
Ok, now it works from the market place.  I was able to install it successfully.  Dont know what was going on.  Thanks.
