### ISSUE TITLE
Feature Request - Customize Tab Title

### ISSUE THREAD

**Issue by saad749** [mayerwin/vs-customize-window-title#17]
Is it possible to have similar functionality, but for tab titles?

For, Example I am interested in a title like:
[documentParentPath:1]\\[documentParentPath:0] 

It helps to have the window display this, but will be more productive to have it in the tabs.

Is it possible to include it in this extension, or it is something entirely different?

**Comment by mayerwin** [comment]
I don't know if it is possible to modify tab titles based on the APIs provided by the Visual Studio extensibility SDK. If you know of another extensions that allows it, do let me know.
However you can already see the full path as a tooltip by just hovering your mouse over the tab name, which is generally good enough. It is quite rare to have multiple files within a solution sharing the same file name, so the use case would likely be limited.
