### ISSUE TITLE
Feature Request - startup project as a selection for title

### ISSUE THREAD

**Issue by bmahnke** [mayerwin/vs-customize-window-title#18]
I would like to submit a new feature, something that was available for a different VS title changer tool that I used for VS 2015, but wasn't available for 2017. 

The startup project as a selection for the title.

Ex:  `Startup Project` - `Solution` 
Ex: `My.Service.Host` - `My.Services.Sln`

**Comment by mayerwin** [comment]
Feature added with version 3.5.0. Please use tags [startupProjectsNames] or [startupProjectsNames:X].
