### ISSUE TITLE
Escape bracket char is broken

### ISSUE THREAD

**Issue by asherber** [mayerwin/vs-customize-window-title#2]
In v.2.8.1, I was able to use `[[gitBranchName]]` to get `[master]` to display. This appears to be broken in v3.2.1 -- what displays is the literal `[[gitBranchName]]`. Is there some other way to escape the bracket char to get it to display?

**Comment by mayerwin** [comment]
Thanks for reporting this regression bug. I have released 3.2.2 which should fix it. You do not need to escape the bracket char, it should work as is. Tags that contains brackets will simply be ignored.
