### ISSUE TITLE
Extension is disabled at startup

### ISSUE THREAD

**Issue by alecava58** [mayerwin/vs-customize-window-title#20]
If I run VS2015 as administrator the extension is enabled. If I run VS2015 as normal user the extension is disabled at startup. If I enable the extension and I close and reopen the IDE the extension is disabled again.

**Comment by mayerwin** [comment]
Hi, I am unable to reproduce this issue. Can you try with VS 2017?

**Comment by mayerwin** [comment]
Weird, there is absolutely nothing in the extension that can control whether it is loaded or not by VS. I'd suggest to reset VS 2015's settings to see if this is caused by a misconfiguration.

**Comment by seagal82** [comment]
just for response +1
I met the same phenomenon
and the workaround works 

> I can confirm I see the same sort of behaviour in VS2015, even with running as an administrator.
> 
> A workaround I found elsewhere which works so far for me is...
> Uninstall the extension
> Restart
> Uninstall the extension if it is still there
> Restart
> ...repeat until it has gone
> Install the extension again
