### ISSUE TITLE
AssemblyInfo is not updated with package version update

### ISSUE THREAD

**Issue by NN---** [mayerwin/vs-customize-window-title#21]
Still points to 3.4.1 and not to 3.6.0

https://github.com/mayerwin/vs-customize-window-title/blob/master/CustomizeVSWindowTitle/Properties/AssemblyInfo.cs

**Comment by mayerwin** [comment]
True, however the assembly version doesn't really matter (the version used for the vsix is in the vsixmanifest).

**Comment by NN---** [comment]
I know. Just dll details seems strange.
