### ISSUE TITLE
changing window title for TFS - Code Review 

### ISSUE THREAD

**Issue by luisll** [mayerwin/vs-customize-window-title#23]
Great tool!
I use TFS, wonder if is there a way configure window title when working on code review.

Kind regards
Luis

**Comment by mayerwin** [comment]
It'd be good if you could post a screenshot of what you're seeing and what you'd want to see ideally. Thanks!

**Comment by luisll** [comment]
when I open a file code review it looks like
![2018-03-01_0955](https://user-images.githubusercontent.com/4409604/36833098-f1de17ee-1d36-11e8-8d0a-8a6f64919f03.png)

I rather have something more friendly like taking the description from the request title, branch, file name etc:
![2018-03-01_0954](https://user-images.githubusercontent.com/4409604/36833163-295960d4-1d37-11e8-9857-7e763806e191.png)
