### ISSUE TITLE
Feature Request - Has unsaved changes / IsAnythingDirty tag

### ISSUE THREAD

**Issue by benneeh** [mayerwin/vs-customize-window-title#24]
When the solution contains unsaved changes, I would like to see that in the title of the window as a *
So i suggest the tag [hasUnsavedFiles] which results in "" when no unsaved files and in "*" when there are unsaved files

**Comment by mayerwin** [comment]
Good idea. Need to figure out if this can be determined simply with the DTE object.

**Comment by Grahamvs** [comment]
@mayerwin, are you able to create a solution / global unsaved tag based on the "DocumentDirtyResolver" that @pstaszko added?

I assume you would be able to iterate through all open documents to check if any are dirty / unsaved?

**Comment by mayerwin** [comment]
@Grahamvs indeed it should be fairly simple. I'll work on it next time I prepare a release (if urgent, feel free to submit a PR).

**Comment by Grahamvs** [comment]
I've created pull request #56 to add an "anythingUnsaved" resolver, but I'm not sure how to link it to this issue.

**Comment by mayerwin** [comment]
Pushing it in a release today. Thanks!
