### ISSUE TITLE
Add indexes to svnDirectoryName similar to path

### ISSUE THREAD

**Issue by ascott23** [mayerwin/vs-customize-window-title#25]
I would like to have the indexing found with the path tag with the svnDirectoryName tag.
For example a branch I'm working on is "/Branches/Developers/\<my name\>/\<branch name\>" and all I really need is \<branch name\>. 
I have a working solution to this if it's ok to submit it

**Comment by mayerwin** [comment]
Hi @ascott23, thanks for the suggestion. Please do submit a PR, much appreciated! I'll do my best to merge it quickly if all looks good.

**Comment by mayerwin** [comment]
Thanks, released with V3.8.0.
