### ISSUE TITLE
Feature request: GitRepository

### ISSUE THREAD

**Issue by lwlwalker** [mayerwin/vs-customize-window-title#27]
Feature request: It would be great if you could add a tag to get the gitrepository, as you have now to get the gitbranchname

**Comment by Memerto** [comment]
Agreed.
It would be nice to see the last commit on the tab so you know if is the last version the one your watching.

**Comment by mayerwin** [comment]
What would be the corresponding git command?

**Comment by WimLeflere** [comment]
I'm also interested in this feature.
This would be the git command according to [StackOverflow](https://stackoverflow.com/a/15716016/2298482)
`git rev-parse --show-toplevel`
