### ISSUE TITLE
NullReferenceException in Visual Studio 2015 on startup

### ISSUE THREAD

**Issue by ScottHutchinson** [mayerwin/vs-customize-window-title#29]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe

ErwinMayerLabs.RenameVSWindowTitle.CustomizeVSWindowTitle.UpdateWindowTitleAsync(object, System.EventArgs)

An unhandled exception of type 'System.NullReferenceException' occurred in CustomizeVSWindowTitle.dll
Object reference not set to an instance of an object.

This **might** be a conflict with the Clang Power Tools extension, which is also not loading correctly.

**Comment by mayerwin** [comment]
Thanks Scott, can you confirm if the issue occurs when the Clang Power Tools extension is disabled?

Also how did you find out about this exception? Was it logged? Normally all exceptions are caught (and logged) to ensure the extension does not crash.

**Comment by ScottHutchinson** [comment]
I found it by debugging VS2015 devenv using VS2017. But I just fixed it: I finally got VS2015 to launch (not quite sure how I did it).

Than Clang Power Tools updated itself to 4.3.2, and now VS is happy again.
See https://github.com/Caphyon/clang-power-tools/blob/master/docs/CHANGELOG.md
