### ISSUE TITLE
Error loading Extension

### ISSUE THREAD

**Issue by DesignStreaks** [mayerwin/vs-customize-window-title#35]
I've just attempted to open VS 2017 and I'm getting a load error.
![VS2017 Extension Error](https://user-images.githubusercontent.com/618612/54508352-d1c9d480-4999-11e9-9af0-0bde28c45ab4.jpg)

From the Activity Log.
![Customize Window Title - Error](https://user-images.githubusercontent.com/618612/54508255-6e3fa700-4999-11e9-8939-e3101a17506d.jpg)

It would seem this is an issue with the latest update as this was working last week, before the update.

Regards,
John

**Comment by mayerwin** [comment]
Thanks, can you check what is the current version of the extension that is installed?

**Comment by mayerwin** [comment]
Is your VS 2017 installation up to date?

**Comment by DesignStreaks** [comment]
Just re-installed the latest Market Place version (4.2.2) and it looks like the updates have solved the problem.
To answer your questions though.
Version of Extension : 4.1.2
Version of VS2017 : 15.5.27128.1
