### ISSUE TITLE
Using TFS branch name in title bar causes random unresponsive UI of up to 30 seconds

### ISSUE THREAD

**Issue by rocifier** [mayerwin/vs-customize-window-title#38]
![image](https://user-images.githubusercontent.com/1772304/54889602-3b059680-4f0a-11e9-9ac7-1a48daeb0117.png)

This error occurs randomly for me throughout the day while using this extension. To reproduce, simply include [tfsBranch] in the windows title setting.

It seems that the external tool takes a significant amount of time to find the current TFS branch. Are we blocking on the UI thread, or awaiting on a separate thread for the I/O?

**Comment by mayerwin** [comment]
I pushed a release a few days ago which should fix this. Can you update to 4.2.3 and tell me if it does indeed resolve this? It was indeed a problem of using the UI thread too much.

**Comment by rocifier** [comment]
Thanks, I have installed it and will test it out this week.

**Comment by mayerwin** [comment]
@rocifier can you confirm this has resolved the issue?
