### ISSUE TITLE
title in taskbar does not match title bar

### ISSUE THREAD

**Issue by paukr** [mayerwin/vs-customize-window-title#39]
Hi,
I have a strange problem. I'm using this format: `[solutionName]\[hgBranchName]`
resulting in a title like so: `Crm\fb-5.3-PRJ-504-1481-api-versioning`

The title is displayed in the the title bar and in the task bar.

but after a few seconds after a build it changes to something ugly like this:
`Crm\fb(fb-5.3-PRJ-504-1481-api-versioning) 5.3PRJ5041481apiversioning`

This ugly string appears only in the task bar (or in output of `tasklist /v`). The title bar in visual studio is displaying the correct string.

When I update the format (add a space) it changes to the correct string again.
This is only happening since the last couple of weeks (can't tell for sure if it was the last update of this extension).

I activated debug mode, but there is nothing logged when the ugly title appears. Can I provide other details to track this down?

**Comment by mayerwin** [comment]
Very strange. The title is only modified in one place, so not sure how we can prevent this.
Can you confirm which version of VS and of the extension you're running?

**Comment by mayerwin** [comment]
When you say you "update the format (add a space)" what do you do exactly?

I wonder if Window may not be interpreting the title name due to the presence of some characters.

**Comment by paukr** [comment]
I found the source of this was VisualHG extension, which adds the branch name (and does the weird stuff to the rest of the title).
I guess the latest update of the Customize Visual Stuido Window Title Extension is causing less updates of the title or different timings.
Is there any place where I could get older versions to try out?

**Comment by mayerwin** [comment]
Yes, you can try older versions here: https://github.com/mayerwin/vs-customize-window-title/releases
Depending on which VS version you're using.
Especially 3.8.1 which was the latest until last month.

There was a change where the extension now has to be loaded asynchronously not to slow down VS. This means it'll take a bit longer initially for the title to be rewritten. But then the triggers (a timer and event-based) should be the same.

**Comment by paukr** [comment]
Ok thanks for the support. VisualHG was causing it.
