### ISSUE TITLE
svnDirectoryName:X

### ISSUE THREAD

**Issue by theKBro** [mayerwin/vs-customize-window-title#40]
Is there any way to "reverse" the index for svnDirectoryName? 
We have multiple projects located in one svn server so we have something like

/prog1/branches/<branch name>
/framework/prog2/branches/<branch name>

and im only interested in the branch name.
Like it is now i cannot set global settings.
Maybe something like [svnDirectoryName:-1]?

**Comment by mayerwin** [comment]
Yes, normally it should be possible to use negative values with the following tags:

**[svnDirectoryName:X]** SVN directory element at the specified index (e.g. for /Branches/Developer/UserName/MySolutionFolder/MySolution.sln, [svnDirectoryName:0] = /, [svnDirectoryName:1] = Branches);

**[svnDirectoryName:X:Y]** SVN directory segment over the specified range (e.g. for /Branches/Developer/UserName/MySolutionFolder/MySolution.sln, [svnDirectoryName:0:2] = /Branches/Developer, [svnDirectoryName:2:0] = Developer/Branches//);

**Comment by mayerwin** [comment]
This isn't supported but I agree it should be. For negative numbers, -1 will be the rightmost element (since -0 is already taken), -2 the second rightmost, etc. I'll implement this today and let you know when you can update.

**Comment by mayerwin** [comment]
Done, please test version 4.3.0 and let me know if you notice any issue.

As per the documentation: 

> Tag arguments X and Y for paths can also be negative numbers, in which case the corresponding path element or range will be resolved backwards, starting from -1 = last path element, -2 = second-to-last path element, etc.

**Comment by theKBro** [comment]
Works like a charm!
