### ISSUE TITLE
Title not set in VS2019 title-bar

### ISSUE THREAD

**Issue by tjgalama** [mayerwin/vs-customize-window-title#44]
I just installed VS2019 (16.0.1) with the plugin (v4.3.3). 
I noticed that the badge in the Windows task-bar has it's title set as configured. 
![image](https://user-images.githubusercontent.com/504789/55884059-b2dced80-5ba7-11e9-9a3e-9309cfd22553.png)

However, the title-bar of VS2019 seems to show the name of the solution only instead of the configured title. 
![image](https://user-images.githubusercontent.com/504789/55884123-cbe59e80-5ba7-11e9-808d-aebfd4047a44.png)

I suppose this has something to do with the new title location in VS2019, but I miss my configured title :-( 
(FYI: when I enable the plugin's debug mode everything look fine)

**Comment by mayerwin** [comment]
Yes, the new box on the right is not the window title, so it is normal the extension isn't modifying it. I don't know yet how this could be achieved (the space is also smaller than the title bar so it could be ugly if the modified text is longer).

**Comment by tjgalama** [comment]
It turns out that the title bar can be restored to it's original location. 
see https://stackoverflow.com/questions/53636350/re-enable-title-bar-in-visual-studio-2019
After that it works fine again !!
