### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. 

### ISSUE THREAD

**Issue by MagicAndre1981** [mayerwin/vs-customize-window-title#50]
VS2017 crashed when I try to close it. DebugDiag shows this stack for `System.ObjectDisposedException`

```
System.ObjectDisposedException    Cannot access a disposed object.    

EnvDTE80.DTE2.get_MainWindow() 
ErwinMayerLabs.RenameVSWindowTitle.CustomizeVSWindowTitle.UpdateWindowTitleAsync(System.Object, System.EventArgs) 
   System.Windows.Forms.Timer.OnTick(System.EventArgs) 
   System.Windows.Forms.Timer+TimerNativeWindow.WndProc(System.Windows.Forms.Message ByRef) 
   System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr) 
```
So MainWindow was already disposed during close and your `UpdateWindowTitleAsync` methode should check this.

_//Edit:_

on next start VS notified me that your extension was the cause:

![image](https://user-images.githubusercontent.com/8274816/62597163-669b8300-b8e5-11e9-9c7f-2f599ed0517d.png)

**Comment by mayerwin** [comment]
Thanks for the report. Fixed with https://github.com/mayerwin/vs-customize-window-title/commit/66a1e408cd5eda9afba1fe69491756e10d62ab8a

**Comment by MagicAndre1981** [comment]
thanks, I'll install the update and see if I get a crash again or not.
