### ISSUE TITLE
Colorize the Title Bar/Change Themes

### ISSUE THREAD

**Issue by jeb1217a** [mayerwin/vs-customize-window-title#52]
Enhancement Request - 
We use TFS and have various branches based on where in the SDC the code is. Typically 
Future -> MainDev -> Main -> Release Testing -> Release.  We also have 3-4 branches off MainDev for large future projects. Names in the title bar helps with where we are but color would be easier to identify the branch.  Having the extension perhaps change the theme applied based on the branch maybe an effective way to do that. I may have 3 copies of VS 2019 running pointing to different development branches but the Solution name and all the file names are the same. Color would indicate ate a glance where I am.

**Comment by mayerwin** [comment]
Thanks for this suggestion. Isn't changing the color theme slow (it is on my computer)? And it would cause it to be changed for any new instance of VS as well :/.

**Comment by deanis74** [comment]
Noting here for posterity - check out the [Solution Colors](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.SolutionColors) extension for this functionality. It works quite well for the different branches we have off of our main dev trunk.
