### ISSUE TITLE
[gitBranchName] is empty for detached head

### ISSUE THREAD

**Issue by mmatrosov** [mayerwin/vs-customize-window-title#54]
The extension is truly awesome! However, [gitBranchName] behaves somewhat unexpectedly in case the repo in a detached head state. Specifically, the tag resolves to an empty string. When I first time installed the extension, I thought the feature was simply not working, since I was in the detached head state. I spent quite some time trying to understand what's happening.

Proposal: use a clear substitution in this case. Something like `detached HEAD`.

**Comment by mayerwin** [comment]
@mmatrosov The resolver for this simply calls `git symbolic-ref --short -q HEAD`. What does it return in your case? I'd just need to know what is the condition to check for to show `detached HEAD` (which indeed seems appropriate).

**Comment by mmatrosov** [comment]
> What does it return in your case?

Empty string.

> I'd just need to know what is the condition to check for to show detached HEAD

From [the docs](https://git-scm.com/docs/git-symbolic-ref): 

> -q
--quiet
Do not issue an error message if the <name> is not a symbolic ref but a detached HEAD; instead exit with non-zero status silently.

Thus it seems like you can either remove `-q` and parse the error message, or check for the return status.

**Comment by mayerwin** [comment]
How can we reliably determine that it is a detached HEAD (and not another error)?

**Comment by mayerwin** [comment]
In your case, what does the command return when you remove` -q`?

**Comment by mmatrosov** [comment]
> How can we reliably determine that it is a detached HEAD (and not another error)?

I'm not sure. Need to investigate.

> In your case, what does the command return when you remove -q?

```
$ git symbolic-ref --short HEAD
fatal: ref HEAD is not a symbolic ref
```

**Comment by mayerwin** [comment]
Is there a separate command we can run to easily check if we're on a detached HEAD (if so, I could run it when the branchName is blank)?

**Comment by mmatrosov** [comment]
I was not able to find a dedicated command line for this.

It seems ok to rely on the fact that `symbolic-ref` return non-zero status if and only if we are in the detached head state. That's what is written in the docs after all.

**Comment by mayerwin** [comment]
Implementing this with today's release. Let me know if it doesn't work as expected!

Thanks for your help.
