### ISSUE TITLE
Show focused tool window?

### ISSUE THREAD

**Issue by DerekSMorin** [mayerwin/vs-customize-window-title#55]
Is it possible to show the focused tool window title?  I do voice programming and we can set up commands to be available depending on what the window title is.  This could be useful for when the terminal is focused, or the find window...

**Comment by mayerwin** [comment]
Interesting use case, I'll try to implement it in the next release (it shouldn't be very difficult). If this is urgent, feel free to submit a PR.

**Comment by DerekSMorin** [comment]
Thanks!  It's not urgent, but if you implement it I will definitely try it out.

**Comment by mayerwin** [comment]
Pushing it in today's release as tag [windowName]. Thanks!

**Comment by DerekSMorin** [comment]
Looks like it is working beautifully!  Thanks!

**Comment by DerekSMorin** [comment]
@mayerwin - it doesn't seem to work for floating tool windows, not sure if that is difficult or not.

Examples:
It works for "Terminal" and "Find and Replace" if the windows are docked inside the visual studio window.  But if either of them are floating, they don't show up in the window title ( even if they have the focus ).

**Comment by mayerwin** [comment]
It works on my end for Solution Explorer for example. Do you have a screenshot (and if you can also tell me which pattern you're using)?

**Comment by mayerwin** [comment]
I cannot see how to create "Terminal" and "Find and Replace" tool windows :/. Are they from an extension?

**Comment by DerekSMorin** [comment]
I put screenshots with how to bring up the windows using the Command Window.
Terminal is fairly new, so depending on your VS version you might not have it.
Find window might also look a bit different.

![image](https://user-images.githubusercontent.com/7568856/82058360-a4a6ae00-9692-11ea-9520-120dd2aa77f4.png)

![image](https://user-images.githubusercontent.com/7568856/82059182-acb31d80-9693-11ea-8cb2-0ac0923dd957.png)

**Comment by DerekSMorin** [comment]
![image](https://user-images.githubusercontent.com/7568856/82059469-13d0d200-9694-11ea-8ad2-7270adfd7ef4.png)

**Comment by mayerwin** [comment]
Just tried this and it works well with the `Find and Replace` window. Did you wait for a few seconds in case there may be some lag? No reason why this tool window would be different than the others. Do you have an open solution in design mode when you're opening this tool window?

For the Terminal Window the command didn't work so my VS version likely doesn't have it. But I think if we can figure out why it doesn't work for you with `Find and Replace`, it'll probably be the same reason.

**Comment by DerekSMorin** [comment]
Seems to be working now.  I've set it up so I can now see title bar in visual studio.  I'll keep my eye on it :)
