### ISSUE TITLE
Add path arguments for git branch name

### ISSUE THREAD

**Issue by bartosz-jarmuz** [mayerwin/vs-customize-window-title#58]
Hello,
Obiviously that's a feature request, not an issue :), but not sure how can I label it as such.
Would it be possible to allow setting the path arguments for git branch name, e.g. [gitBranchName:1]

The use case is - we have a project where branches are like so
/Production/1.0
/Production/2.0
/Production/1.0/dev/user/feature

So, with this approach, if I have a version 2.0 branch open, along with 1.0/dev/user/feature, my VS window title is not helpful, as it shows only "Producti....".
It would be good to see "1.0" or "user/feature" for example.

Cheers
Bartosz

**Comment by RichardSinden** [comment]
How about an option to add a regex, and take either the first/last/all capture groups that have something in? 
Then, for the case above, you could write some like this: `/Production/([\d\.]+)$|/dev/(\w+/\w+)$` (this regex could probably be better written, but hopefully it illustrates my point). 
This would make it very flexible.
