### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by justin-romano** [mayerwin/vs-customize-window-title#6]
Trying to use Solution override
![image](https://cloud.githubusercontent.com/assets/1707226/21029887/b85a909c-be00-11e6-81ab-062662d564d7.png)
Seems to have no affect
![image](https://cloud.githubusercontent.com/assets/1707226/21029930/e1597ddc-be00-11e6-8aec-318a56f38a46.png)

**Comment by mayerwin** [comment]
It seems you have written SolutionName instead of solutionName, haven't you? The tags are case sensitive.
Let me know if this fixes the issue.
