### ISSUE TITLE
Support title in compact menu

### ISSUE THREAD

**Issue by jcplan** [mayerwin/vs-customize-window-title#60]
Support change of the **title** when using the **compact menu in VS 201**9.

The compact menu can be activated in Visual Studio 2019 in _Tools -> Options -> Environment -> Preview Features -> Use compact menu and search bar_.

Without the compact menu:
![VS 2019 no compact menu](https://user-images.githubusercontent.com/74242448/100225601-be1c9280-2f1e-11eb-8810-6036c3eec30f.png)

With the compact menu - see the solution title to the right:
![VS 2019 compact menu](https://user-images.githubusercontent.com/74242448/100225721-f328e500-2f1e-11eb-83f1-f667e2f50427.png)

**Comment by mayerwin** [comment]
I already looked into it previously and with the compact menu, it is only the solution name that is displayed. It doesn't seem possible to customize it (at least not easily).

**Comment by szliu-a** [comment]
Can an additional text label be added? Like adding another menu after "Help" showing the title.
