### ISSUE TITLE
Issue with [svnDirectoryName] not working

### ISSUE THREAD

**Issue by LeoG71** [mayerwin/vs-customize-window-title#61]
Here is what I have it set up as. In this setup I don't have admin right in this Virtual Machine.
![image](https://user-images.githubusercontent.com/8144582/102407081-21936080-3fb1-11eb-8b30-9b3cc762c4a1.png)

Here is the log requested when debugging is enabled. 
```
CustomizeVSWindowTitle: SvnResolver.GetSvnDirectory() exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ErwinMayerLabs.RenameVSWindowTitle.Resolvers.SvnResolver.GetSvnDirectory(String workingDirectory)
CustomizeVSWindowTitle: SvnResolver.GetSvnDirectory() exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ErwinMayerLabs.RenameVSWindowTitle.Resolvers.SvnResolver.GetSvnDirectory(String workingDirectory)
CustomizeVSWindowTitle: SvnResolver.GetSvnDirectory() exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ErwinMayerLabs.RenameVSWindowTitle.Resolvers.SvnResolver.GetSvnDirectory(String workingDirectory)
CustomizeVSWindowTitle: SvnResolver.GetSvnDirectory() exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ErwinMayerLabs.RenameVSWindowTitle.Resolvers.SvnResolver.GetSvnDirectory(String workingDirectory)
```

**Comment by mayerwin** [comment]
Looks like the issue is that it can't find the executable. Are you sure the SVN binaries directory is correct?
Since you're not launching VS as an administrator, are you able to run svn.exe?

**Comment by mayerwin** [comment]
Here is the relevant file/function that fails: https://github.com/mayerwin/vs-customize-window-title/blob/9e91d2ac36e678e3ce8bf91a84ff7744871636b2/CustomizeVSWindowTitle/Resolvers/SvnResolver.cs#L77

**Comment by LeoG71** [comment]
Yes. SVN works just fine. I can commit and update repo without any issues.
Your extension worked about 6 months ago even without the SVN directory
defined.

**Comment by mayerwin** [comment]
Is the SVN binaries directory added to the machine PATH (i.e. can you run svn.exe from the command line without specifying a path)? If so, you should not need to specify the binaries path in Visual Studio.

**Comment by LeoG71** [comment]
I can't edit the environment variable for path as I don't have admin
rights. We use TortoiseSVN and also TortoiseGit. I don't know if they are
conflicting as your extension can be configured for both.

**Comment by mayerwin** [comment]
No chance they'd conflict.

Even if you can't edit the PATH variable, can you just check if svn.exe works in a command line (if it does it means it is added to the PATH)?

If it was working 6 months ago without specifying the SVN directly it means for sure the SVN directory was added to the PATH at the time.

**Comment by LeoG71** [comment]
I will play on my own laptop. Please keep that ticket open for right now.
Thanks

**Comment by LeoG71** [comment]
One more question. Why does ankhsvn plugin work in SSDT but not yours? Just
a thought.

**Comment by mayerwin** [comment]
> One more question. Why does ankhsvn plugin work in SSDT but not yours? Just a thought.

No idea.

**Comment by LeoG71** [comment]
There is no issue. TortoiseSVN by default did not install svn.exe.
