### ISSUE TITLE
Feature request - Allow to remove prefixes separated with dot character

### ISSUE THREAD

**Issue by alukycode** [mayerwin/vs-customize-window-title#69]
Hello!

I found this extension while trying to solve the following issue.

I have the following solution names:
- Company.Department.FirstServiceName.sln
- Company.Department.SecondServiceName.sln
- Company.Department.ThirdServiceName.sln

Full name doesn't fit in the taskbar, so in result I see just 'Company.Department...'
It will be nice to have the variable that allows to display part of the solution name relying on dot characters.
I see the usage of this variable like this: [solutionName:itemsToSkip] -> [solutionName:1] -> Department.FirstServiceName.sln

**Comment by alukycode** [comment]
Is there any alternative solution for my issue that I can try?
Are there better ideas how this can be implemented?

**Comment by mayerwin** [comment]
@alukycode Do you know that you can always use a XML config file specific to each solution, and then inside it, simply hardcode the equivalent of solutionName to look exactly like you want? It seems it'd be a better solution here as the pattern you're suggesting likely wouldn't work well with other solution names then (so not appropriate to configure this at the IDE level, for all solutions that may be loaded). Let me know if you have any difficulty generating the config file (there is a function exactly for that in the extension settings, so you don't need to write it from scratch).
