### ISSUE TITLE
Display TFS Branch Name?

### ISSUE THREAD

**Issue by MarkEdward-BarS** [mayerwin/vs-customize-window-title#7]
Hi,

I was wondering if it is possible to include branch names from TFS, like you can with Git?

Thanks for a great little utility, even without being able to get TFS branch names, simply being able to show directory names is enormously useful in identifying which branch you're working on.

Thanks again, Mark

**Comment by mayerwin** [comment]
Hi, it should be possible, but I am not very familiar with TFS automation. Please take a look at https://github.com/mayerwin/vs-customize-window-title/blob/master/RenameVSWindowTitle/WorkspaceInfoGetter.cs and feel free to submit a PR to add support for retrieving the workspace branch name?

**Comment by mayerwin** [comment]
If this information is obtainable through command line (like with git), it could also be a solution. Can you tell me if the following works for you: http://stackoverflow.com/questions/10332269/how-to-determine-branch-name-from-batch-file

**Comment by mrsesch** [comment]
You can look here:
https://github.com/squaredinfinity/VSCommands/blob/master/Sources/Shared/Integration/TeamFoundation/TeamFoundationHelper.cs

With vsCommands it is possible. The drawback of vsCommands is that it is not available for VS 2017 yet.

**Comment by mayerwin** [comment]
Thanks for the link. I'll check that.

**Comment by mayerwin** [comment]
The dependency on a Nuget package seems quite heavy, it would be better if someone who uses TFS could test adding the missing method using the current implementation (that is derived from https://github.com/pasztorpisti/vs-window-title-changer/blob/5959685e246df8054a363b736d91553d0c526c79/ExpressionEvaluator/EvalTree_ProjectSpecific.cs and loads the DLL dynamically), and submit a PR. If it is not possible, then I'll consider adding the dependency.

**Comment by mayerwin** [comment]
I tried some things with DLLs but it really seems to bloat the extension with plenty of dependencies (I like the fact that it currently fits in 115kB).
I believe there is a command line tool installed with TFS, that works like with Git and Mercurial. Could you just give me the commands used to obtain the branch name?

If so, it should be quite straightforward to implement as I would reuse the same logic and UI as for Git and Mercurial (which use the already installed command line tool or allow the user to override its path).

**Comment by tjgalama** [comment]
I tried it with TF.exe (default installed) and TFPT.exe (which is part of VS2015 extension- TFS Power Tools). Unfortunatly no luck. 
I think including the Microsoft.TeamfoundationServer.Client (or perhaps Microsoft.VisualStudioServices.Client?)  is the only valid way to make this work for branche
Depending on how consistent a developer organizes it's source-control, this issue 'might' also be solved by supporting regex in the title patterns (in some-way)

**Comment by timhaovo** [comment]
A [tfsBranchName] tag would be very useful, indeed!

This is what I used in a different project to get the TFS branch name by calling GetBranchNameFromLocalFile with the solution folder as argument:
https://pastebin.com/fx2hu0iJ

**Comment by mayerwin** [comment]
Thanks a lot, I can see it requires NuGet package Microsoft.TeamFoundationServer.ExtendedClient. It'd really be ideal if it could be extracted with TF.exe (whatever the complexity of the regex), do you know if this would be possible?

**Comment by timhaovo** [comment]
I'm not aware of any TF.exe command that would reliably output the nearest branch or identify a folder as a branch, sadly.

However, TF.exe does reference the assemblies required to execute the code above. So a hack-ish solution could be to use these assemblies instead. At design time you could reference the assemblies from the TF.exe folder with CopyLocal=false, to prevent inclusion in the final build. Then use the AppDomain.CurrentDomain.AssemblyResolve event to manually resolve the assemblies from the TF.exe folder during runtime. Not very reliable, but any resolving or missing assembly exceptions can be caught to gracefully fail in these cases.

The required assemblies are:
Microsoft.TeamFoundation.Client
Microsoft.TeamFoundation.Common
Microsoft.TeamFoundation.VersionControl.Client
Microsoft.TeamFoundation.VersionControl.Common
Microsoft.VisualStudio.Services.Client.Interactive
Microsoft.VisualStudio.Services.Common

Example assembly resolve handler:
`        private static System.Reflection.Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            if (args.Name.StartsWith("Microsoft.TeamFoundation.") || args.Name.StartsWith("Microsoft.VisualStudio.Services."))
            {
                string name = args.Name;
                int spos = name.IndexOf(',');
                if (spos >= 0)
                    name = name.Substring(0, spos);
                var path = System.IO.Path.Combine(TFExeFolder, name + ".dll");
                return System.Reflection.Assembly.LoadFile(path);
            }
            return null;
        }`

**Comment by timhaovo** [comment]
Oh, it's even easier, because Visual Studio has all these assemblies loaded by default as soon as a solution is opened. So no need to include or even resolve the assemblies at all, the extension can just use whatever Visual Studio has loaded anyway.

All you have to do to get the code working:

1) Reference the required assemblies. These are:

Microsoft.TeamFoundation.Client
Microsoft.TeamFoundation.Common
Microsoft.TeamFoundation.VersionControl.Client
Microsoft.TeamFoundation.VersionControl.Common
Microsoft.VisualStudio.Services.Client.Interactive
Microsoft.VisualStudio.Services.Common

You'll find them in the TF.exe path (for VS2017 community edition: Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer )

For each of these references, set "_Specific version_" and "_Local copy_" to _false_, because you want to use whatever comes with Visual Studio at runtime.

2) Put the [TfsHelper class](https://pastebin.com/cbiAYHPU) into the project.

3) To get the TFS branch name call _TfsHelper.GetBranchNameFromLocalFile with_ the directory path of the current solution (not the .sln file itself, because it might not be in TFS even if the folder is). Make sure to wrap the call in a try/catch block to protect against cases where the assemblies may fail to load for whatever reason.

**Comment by mayerwin** [comment]
Thanks, I'll look into integrating this feature in the next version (the one which will support VS 2019).

**Comment by mayerwin** [comment]
Could this be achieved with this upcoming feature: https://github.com/mayerwin/vs-customize-window-title/issues/33

**Comment by timhaovo** [comment]
> Could this be achieved with this upcoming generic feature?
> #33

There is no official command line tool that can provide the TFS branch name for a given file or folder. It'd be possible to write a tool like that, of course, but i think the ability to display the TFS branch name in the Visual Studio title bar is so close to the core feature set of this extension that it'd be weird if it required the download of an additional command line tool to get it to work.

**Comment by mayerwin** [comment]
Indeed. I think I'll try to implement the solution you suggested which seems fair enough!

**Comment by mayerwin** [comment]
Do you know if the solution proposed here: https://stackoverflow.com/a/10332745/541420 could work to extract the branch name? (`TF.EXE properties .`)
For parity with git and hg it'd still be best if we could use tf.exe :).

**Comment by timhaovo** [comment]
No, sadly not. tf properties or tf info report the full server path, but it's not possible to determine which part of the path represents the branch.

**Comment by rocifier** [comment]
Hi, any progress on this? Anything I could do to help? I would use this feature daily at work.

**Comment by mayerwin** [comment]
Hi, I'll try to get it done alongside the new release this month to support VS 2019. I'll let you know if I need your help for testing, thanks!

**Comment by rocifier** [comment]
That would be awesome, I'll try to stand by to test it, as we use TFS extensively (for better or worse, it's a difficult move out).

**Comment by mayerwin** [comment]
Hello, I have implemented support for TFS branch name using the solution suggested by @timhaovo. The new tag is [tfsBranchName] Can you please try the following VSIX and confirm if it works as you expect, if possible in VS 2015, 2017 and 2019?
[CustomizeVSWindowTitle (new).zip](https://github.com/mayerwin/vs-customize-window-title/files/2974869/CustomizeVSWindowTitle.new.zip)

**Comment by rocifier** [comment]
Oh what a champion, I'll try it out tomorrow hopefully. How do I configure it?

**Comment by mayerwin** [comment]
Just use the tag [tfsBranchName] in the patterns you want.

**Comment by mayerwin** [comment]
(in the "Custom VS Window Title" section of Visual Studio's Settings)

**Comment by rocifier** [comment]
Hi @mayerwin just tested on VS2017 and VS2015. Results:

VS2017
=====
When using [tfsBranchName] I see a single aterisk '*' shown in place of the where I expect the branch name. Tested for two different solutions, one on Main, one on a private branch.

VS2015
=====
![image](https://user-images.githubusercontent.com/1772304/54497625-c5c22080-4961-11e9-9f07-ec09da9e6a7a.png)

Was unable to notice any messages in Output tabs related to the plugin.

Thanks,
Ryan

**Comment by mayerwin** [comment]
Thanks, can you try again with the latest version (4.2.0)?

**Comment by timhaovo** [comment]
I tried version 4.2.0, but the [tfsBranchName] placeholder just results in an empty string. My VSIX test project with the TfsHelper sample code above reports the correct branch, though. This is a very busy week for me, so i can't do much in-depth debugging right now. But i'll probably have time to look into it some more next week.

**Comment by mayerwin** [comment]
Can you give me an example of this:

>  call TfsHelper.GetBranchNameFromLocalFile with the directory path of the current solution (not the .sln file itself, because it might not be in TFS even if the folder is). 

I may not have implemented this properly.

**Comment by timhaovo** [comment]
Sure, i do this in my test VSIX project:
```C#
var localDTE = (EnvDTE.DTE)(await package.GetServiceAsync(typeof(EnvDTE.DTE)));
var file = System.IO.Path.GetDirectoryName(localDTE?.Solution?.FullName);
var branch = GetTfsBrnachFromFile(file);
```

**Comment by tjgalama** [comment]
I don't see the branch name either. Might it have something to do with the fact that I have the _Enterprise_ edition? let me know If you need additional info/logging.

**Comment by mayerwin** [comment]
OK strange, here is the code calling TfsHelper:

 ```
       public static string GetBranchNameOrEmpty(Solution solution) {
            var sn = solution?.FullName;
            if (string.IsNullOrEmpty(sn)) return string.Empty;
            var name = string.Empty;
            Globals.InvokeOnUIThread(() => name = TfsHelper.GetBranchNameFromLocalFile(Path.GetDirectoryName(sn)));
            return name ?? string.Empty;
        }
```

**Comment by mayerwin** [comment]
And I have put the TfsHelper here: https://github.com/mayerwin/vs-customize-window-title/blob/master/CustomizeVSWindowTitle/Lib/TfsHelper.cs

Not sure what is not set up correctly.

**Comment by mayerwin** [comment]
@tjgalama No I don't think it has anything to do with that. The right way to debug this would be to have a test project and just place a breakpoint to understand why the resolver doesn't work. I have not tested it myself as I am not using TFS, so I have blindly implemented the code by @timhaovo (which likely is good but I may have overlooked something).

**Comment by timhaovo** [comment]
Tried my test project with the TfsHelper code you are using and it stops working. The culprit is the cast of vssCredentials to ICredentials in CreateTfsCollection. Use vssCredentials  without the cast and and works again.

**Comment by tjgalama** [comment]
One other thing; when updating the package the VS Options for title customization were reset.

**Comment by tjgalama** [comment]
When I enabled Debug mode the following exception turned up in the output view:
```
CustomizeVSWindowTitle: ReplaceTag (tfsBranchName) failed: System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.Services.Common.VssCredentials' to type 'System.Net.ICredentials'.
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.Lib.TfsHelper.CreateTfsCollection(String tfsName)
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.Lib.TfsHelper.GetBranchNameFromLocalFile(String path)
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.Resolvers.TfsBranchNameResolver.<>c__DisplayClass2_0.<GetBranchNameOrEmpty>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.Globals.InvokeOnUIThread(Action action)
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.Resolvers.TfsBranchNameResolver.GetBranchNameOrEmpty(Solution solution)
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.Resolvers.TfsBranchNameResolver.Resolve(AvailableInfo info)
   at ErwinMayerLabs.CustomizeVSWindowTitleExtension.CustomizeVSWindowTitle.<>c__DisplayClass53_0.<GetNewTitle>b__0(Match match)
```

**Comment by mayerwin** [comment]
Hi, can you try to update to version 4.2.2 (on the marketplace)?
I have removed the cast for vssCredentials, and reverted the namespace change which may be causing the previous options to be lost (I don't see what else could be causing this), please confirm if they're back. Thanks!

**Comment by timhaovo** [comment]
v4.2.2 works! Thanks a lot for integrating this feature!

**Comment by mayerwin** [comment]
Thank you for your help to get this implemented and working (and I am happy as the extension remains very lightweight)!
