### ISSUE TITLE
Adding "Substring" functionality

### ISSUE THREAD

**Issue by kp-gl** [mayerwin/vs-customize-window-title#72]
First a BIG THANK YOU for this great extension!

It would be handy to have the ability to only use the first (or some from the beginning) characters from specific [Elements] - in order to save space on the task bar button.
(like [solutionName%0,1]) to get only the first letter of the solution name)

EDIT: I assume it would be sufficent to only specify the length

**Comment by mayerwin** [comment]
@kp-gl  Do you know that you can always use a XML config file specific to each solution, and then inside it, simply hardcode the equivalent of solutionName to look exactly like you want? It seems it'd be a better solution here as the pattern you're suggesting likely wouldn't work well with other solution names then (so not appropriate to configure this at the IDE level, for all solutions that may be loaded). Let me know if you have any difficulty generating the config file (there is a function exactly for that in the extension settings, so you don't need to write it from scratch).
