### ISSUE TITLE
Customizable Font Family

### ISSUE THREAD

**Issue by ftovagliari** [mayerwin/vs-customize-window-title#74]
I propose adding the option to set a custom font family.
The reason is to enable the insertion of icons within the title using for example one of the Nerd Fonts (https://www.nerdfonts.com/). Currently, the only option available (as far as I know) is to change the font family for the entire Visual Studio environment. Unfortunately, the rendering of Nerd fonts in Visual Studio is suboptimal, significantly impacting the overall user experience.

I attach a screenshot with the "M+1Nerd Font" font family and one with the automatic VS font family (the difference is not noticeable when viewing the images from the browser).
![image](https://github.com/mayerwin/vs-customize-window-title/assets/582712/2053aba4-4447-4924-a479-d75b1ce44905)

![image](https://github.com/mayerwin/vs-customize-window-title/assets/582712/54467f44-acac-4559-b3c5-77615414dfaa)

**Comment by mayerwin** [comment]
Thanks, but not sure how you think this could be achieved?
