### ISSUE TITLE
Feature Request: use scc plugin if one is enabled

### ISSUE THREAD

**Issue by Skylark13** [mayerwin/vs-customize-window-title#76]
Hello,

At work we use Perforce, and I also use git for various OSS projects or things I get on github. I think it would be nice if the plugin could see that for a given solution, a source control plugin is enabled, and if so, use that to get the current branch name or other info the plugin wants to display. It could be a separate tag if you want, like `[sccBranchName]` and so on, so that people who always work with git could continue using `[gitBranchName]` if they want. But depending on your Visual Studio settings, `[sccBranchName]` would work for solutions under git, Perforce, or anything else without having to change the configuration, as long as the solution has the right source control provider.

I wanted to have a go at implementing this, but I'm having trouble getting my bearings in the Visual Studio scc plugin API. So I'm posting this here in case someone else thinks this would be useful and wants to have a go at it.

**Comment by mayerwin** [comment]
Do you know that you can always use a XML config file specific to each solution (that takes precedence over the IDE's settings), so it can be exactly like you want (using the right branchName tag for the SCC the solution is in, among a lot of other possibilities)? 
It seems it'd be a better solution for this use case than adding a new tag to minimize complexity, at least until more people complain (I wouldn't mind merging a pull request as your use case is still legit). Let me know if you have any difficulty generating the config file (there is a function exactly for that in the extension settings, so you don't need to write it from scratch).

**Comment by Skylark13** [comment]
I did not know about the XML config file functionality, thanks for letting me know. 

The problem with that is that a Perforce workspace (mapped to a local folder on your computer) can switch between different branches (or streams). The path on the local machine does not indicate which branch you are currently in. If we don't add tags to use the source control provider, I think we'll need at a minimum to add tags to support perforce the same way git, mercurial etc are supported (via running a command line to get the information we want).
