### ISSUE TITLE
Workspace isn't updating

### ISSUE THREAD

**Issue by ori-emrlive** [mayerwin/vs-customize-window-title#9]
When jumping from workspace to workspace in Team Explorer, the Workspace name in the Title doesn't update.

**Comment by mayerwin** [comment]
Hi, do you mean this will load a new solution? Currently the workspace name is indeed cached, as with git for example the branch name will not typically change (tied to the directory of the opened solution). I am not using Team Explorer myself so I am not too familiar with the workflow.

**Comment by mayerwin** [comment]
Actually after checking this further the workspace name is not cached, but is determined based on the currently loaded solution. If you are seeing this issue where the solution loaded does not match the workspace name please advise, if not I guess what you are after would have to be determined by checking the selection in Team Explorer.
